const IPC_ERROR_CODES = {
  IPC_HANDLER_FAILED: "IPC_HANDLER_FAILED",

  APP_PING_FAILED: "APP_PING_FAILED",
  APP_INFO_FAILED: "APP_INFO_FAILED",

  WECHAT_WINDOW_CONTEXT_FAILED: "WECHAT_WINDOW_CONTEXT_FAILED",
  WECHAT_STATUS_DETAIL_FAILED: "WECHAT_STATUS_DETAIL_FAILED",
  WECHAT_FOCUS_WINDOW_FAILED: "WECHAT_FOCUS_WINDOW_FAILED",
  WECHAT_QUICK_SEND_FAILED: "WECHAT_QUICK_SEND_FAILED",
  WECHAT_CAPTURE_WINDOW_FAILED: "WECHAT_CAPTURE_WINDOW_FAILED",
  WECHAT_LIST_CAPTURES_FAILED: "WECHAT_LIST_CAPTURES_FAILED",
  WECHAT_CLEANUP_CAPTURES_FAILED: "WECHAT_CLEANUP_CAPTURES_FAILED",
  WECHAT_STATUS_NOT_NORMAL: "WECHAT_STATUS_NOT_NORMAL",
  WECHAT_RECT_MISSING: "WECHAT_RECT_MISSING",

  RPA_MOUSE_MOVE_FAILED: "RPA_MOUSE_MOVE_FAILED",
  RPA_MOUSE_CLICK_FAILED: "RPA_MOUSE_CLICK_FAILED",
  RPA_KEYBOARD_KEY_FAILED: "RPA_KEYBOARD_KEY_FAILED",
  RPA_TYPE_TEXT_FAILED: "RPA_TYPE_TEXT_FAILED",

  RUNTIME_STATE_FAILED: "RUNTIME_STATE_FAILED",
  RUNTIME_EVENT_FAILED: "RUNTIME_EVENT_FAILED",
  RUNTIME_INVALID_TRANSITION: "RUNTIME_INVALID_TRANSITION",
  RUNTIME_UNKNOWN_EVENT: "RUNTIME_UNKNOWN_EVENT",
};

module.exports = {
  IPC_ERROR_CODES,
};

